### ISSUE TITLE
Check if chains have ICA controller functionality implemented

### ISSUE THREAD

**Issue by womensrights** [charleenfei/interchain-version-fetcher#2]
For tracking feature adoption it would be really useful if the script could be modified to check the app.go file for chains to see whether they have ica and icacontroller functionality enabled. 

For example, looking for  - 	

ica "github.com/cosmos/ibc-go/v3/modules/apps/27-interchain-accounts"
icacontroller "github.com/cosmos/ibc-go/v3/modules/apps/27-interchain-accounts/controller"

found in the [app.go file of stride](https://github.com/Stride-Labs/stride/blob/main/app/app.go#L94-L95)

**Comment by charleenfei** [comment]
addressed with the latest commit :)
